name: updateListOfPlaces

on:
  workflow_dispatch:
#  schedule:
#    - cron: "0 14 * * *"  # runs at 14:00 UTC everyday
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute py script # run the run.py to get the latest data
        run: |
          python main.py
      - name: Commit files
        id: commit
        run: |
          git pull
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add --all
          if ["$(git status --porcelain)" == ""]; then
            echo "nothing to commit"
            echo "::set-output name=push::false"
          else
            echo "changes found"
            git commit -m "Add new places" -a
            echo "::set-output name=push::true"
          fi
        shell: bash
    
      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
